# This workflow to automatically build and deploy to Firebase Hosting (deployment branch)
# when code is pushed to the main branch
name: Build and Deploy

# Controls when the action will run. 
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      #This is required if build folder is in .gitignore, which it likely is
      - name: Create build folder output
        run: mkdir -p dist/mangajap

      # Install packages and build project
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build:prod

      # Deploy to master
      - name: Deploy 🚀
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
